version: "3.9"

services:
  mariadb:
    build: ./requirements/mariadb/.
    image: mariadb:42
    container_name: mariadb
    hostname: mariadb
    networks:
      - net
    volumes:
      - v-db:/var/lib/mysql
    env_file:
      - .env

  # wordpress:
  #   build: ./requirements/wordpress/.
  #   image: wordpress:42
  #   container_name: wordpress
  #   hostname: wordpress
  #   env_file:
  #     - .env
  #   networks:
  #     - net
  #   volumes:
  #     - v-wordpress:/var/www/wordpress
  #   depends_on:
  #     - mariadb

  nginx:
    build: ./requirements/nginx/.
    image: nginx:42
    container_name: nginx
    hostname: nginx
    ports:
      - 443:443
    env_file:
      - .env
    networks:
      - net
    volumes:
      - v-wordpress:/var/www/wordpress
    depends_on:
      - mariadb
      - wordpress


  
volumes:
  v-wordpress:
    name: v-wordpress
    driver: local
    driver_opts:
      device: ./requirements/wordpress/volume
      o: bind
      type: none

  v-db:
    name: v-db
    driver: local
    driver_opts:
      device: ./requirements/mariadb/volume
      o: bind
      type: none

networks:
  net:
    name: net
    driver: bridge
