version: "3.9"

services:
  mariadb:
    build: ./requirements/mariadb/.
    image: mariadb:42
    container_name: mariadb
    networks:
     - db-net
    volumes:
      - db-v:/var/lib/mysql
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress/.
    image: wordpress:42
    container_name: wordpress
    env_file:
      - .env
    depends_on:
      - mariadb

  nginx:
    build: ./requirements/nginx/.
    image: nginx:42
    container_name: nginx
    ports:
      - 443:443
    env_file:
      - .env
    depends_on:
      - mariadb
      - wordpress


  
volumes:
  wordpress-v:
    name: wordpress-v
    driver: local
    driver_opts:
      device: ./requirements/wordpress/volume
      o: bind
      type: none

  db-v:
    name: db-v
    driver: local
    driver_opts:
      device: ./requirements/mariadb/volume
      o: bind
      type: none

networks:
  nginx-net:
    name: nginx-net
    driver: bridge
  db-net:
    name: db-net
    driver: bridge
