version: "3.9"
services:
  nginx:
    build: ./requirements/nginx/.
    image:  nginx:42
    container_name: nginx
    ports:
      - "433:433"
    env_file:
      - .env

  # wordpress:
  #   depends_on:
  #     - maria-db
  #   build: ./srcs/requirements/wordpress/.;

  # maria-db:
  #   build: ./srcs/requirements/mariadb/.
  
# volumes:
#   wordpress:
#     name: "wordpress"
#   db-data:
#     name: "db-data"


# networks:
#   nginx-net:
#   db-net: