version: "3.9"

networks:
  network1:
    name: test-net
    external: true 

services:
  nginx:
    build: ./requirements/nginx/.
    image:  nginx:42
    container_name: nginx
    ports:
      - 443:443

  # wordpress:
  #   depends_on:
  #     - maria-db
  #   build: ./srcs/requirements/wordpress/.;

  # maria-db:
  #   build: ./srcs/requirements/mariadb/.
  
# volumes:
#   wordpress:
#     name: "wordpress"
#   db-data:
#     name: "db-data"

# networks:
#   nginx-net:
#     name: nginx-net
#     driver: host
#   db-net: